"""Secound

Revision ID: bb4d20b2f415
Revises: 
Create Date: 2025-09-26 08:56:56.429977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4d20b2f415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('password_master', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_type_', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('password_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['password_id'], ['Passwords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Media')
    op.drop_table('Passwords')
    op.drop_table('Users')
    # ### end Alembic commands ###
